#server:
#  error:
#    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:sqlserver://10.10.10.2:1433;databaseName=master
    username: sa
    password: )()(#p0oqwe@01
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
#      ddl-auto: create-drop
